### ISSUE TITLE
Connecting Db-toolkit to other databases

### ISSUE THREAD

**Issue by adminmirra** [Desertsnowman/DB-Toolkit#3]
Hello,

DB-Toolkit is an awesome plugin, actually the best I have ever seen on wordpress and when comparing to any other plugin, this is really the powerful one.

Is there any possibility, how to let DB-toolkit connect to the other databases?  I was really trying, but without success.
For example, I have database named "hello" where wordpress with dbtoolkit is in. 
I would like to create a new APP in db-toolkit with new interface, which will connect to the database "byebye" into tab "mine_bye". 
Is there any possibility how to do this? 

I understand, you don't probably have a time right now (i heard about pods), but if you don't want to add an option, which database and tab to choose, let me know please, where should I edit some php code, to "enable" this functionality.

Sry for my english, but with this plugin, it lets me write you even my english is not so good. 

Thank you and Best Regards (I am using WP 3.7.2 which is working great with DB-Toolkit 0.3.3) 
MIrra

**Comment by DavidCramer** [comment]
This is an answer to an issue for 2013. Since I'm planning on resurrecting it, it's time to address requirements. And yes, a requirement should be to connect to any accessible MySQL database.

But since this is an old issue, I'll archive it and make sure it's noted.
