### ISSUE TITLE
Appending GET options to redirected URLs

### ISSUE THREAD

**Issue by gwythaint** [Desertsnowman/DB-Toolkit#4]
I think this itty bitty change vs. 0.3.3 lets FORM mode interfaces send passback fields to targets of redirects by letting $ReturnValue keep its originally assigned value.
Otherwise, http_build_query() will fall over itself operating on unsigned $gets.

<pre>
diff --git a/libs/functions.php b/libs/functions.php
index 7fbb9ac..373efcf 100644
--- a/libs/functions.php
+++ b/libs/functions.php
@@ -1382,8 +1382,8 @@ function dt_process() {
                     }
                     $ReturnValue = htmlspecialchars_decode(@http_build_query($gets, $returngets));
 
-                }
                 $Redirect = $Location.$returntoken.$ReturnValue;
+                }
             }
             //echo $Redirect;
             //exit;
</pre>

**Comment by DavidCramer** [comment]
This will be a core feature in future.
