### ISSUE TITLE
API Mode requires mod_redirect

### ISSUE THREAD

**Issue by gwythaint** [Desertsnowman/DB-Toolkit#5]
I think it is under appreciated that interfaces set to API Mode need mod_redirect and possibly a wordpress permalink setting to something other than default.

The default wordpress redirect rules under .htaccess prevent 
evaluation of "CallName / Key/Token / Method / Format / ? GET Variables"

**Comment by DavidCramer** [comment]
a feature that is almost a requirement when dealing with permalinks. This will be addressed and made available if said module is enabled.
